services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: ecommerce_sqlserver_user
      POSTGRES_PASSWORD: C9smJ6lUL0qUpP6tLKsOag6d1RjZcoOC
      POSTGRES_DB: ECommerceCatalog   # initial database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  catalog-api:
    build:
      context: .                 
      dockerfile: src/Catalog.API/Dockerfile
    container_name: catalog-api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ECommerceCatalog;Username=ecommerce_sqlserver_user;Password=C9smJ6lUL0qUpP6tLKsOag6d1RjZcoOC
    depends_on:
      - postgres
    networks:
      - ecommerce-net
    
  identity-api:
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    container_name: identity-api
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ECommerceCatalog;Username=ecommerce_sqlserver_user;Password=C9smJ6lUL0qUpP6tLKsOag6d1RjZcoOC
    depends_on:
      - postgres
    networks:
      - ecommerce-net

  basket-api:
    build:
      context: ./src
      dockerfile: Basket.API/Dockerfile
    container_name: basket-api
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis

  web-app:
    build:
      context: ../ecommerce-web-app/ecommerce-web-app 
      dockerfile: Dockerfile
    container_name: ecommerce-web-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data: